- .github/PULL_REQUEST_TEMPLATE.md
#14 
이제 pull request시 자동으로 아래 템플릿이 추가됩니다.
pull request 기본 템플릿 추가
```
```
> pull request 기본 템플릿 추가

- commit-convention.md
> commit-convention 추가

- front/src/UI/atoms/NavIcon/index.scss
- front/src/UI/atoms/NavIcon/index.tsx
navigation 이쁘게 css 입혔습니다.
none
none
> feat: nav css 구현 (hover)

- front/src/App.tsx
- front/src/UI/atoms/AlarmMessage/index.tsx
- front/src/UI/atoms/index.tsx
- front/src/UI/molecules/AlarmChat/index.tsx
- front/src/UI/molecules/AlarmNotifier/index.tsx
- front/src/UI/molecules/AlarmUser/index.tsx
- front/src/UI/molecules/ProfileSmall/index.tsx
- front/src/UI/molecules/index.tsx
- front/src/UI/organisms/Alarm/index.tsx
https://github.com/transcendence42/ft_transcendence/pull/24 다음 풀리퀘 리뷰 먼저 선행돼야합니다.
알림 구현 완료.
> alarm 알림 구현 완료

- start-server.sh
- stop-server.sh
> feat: docker start stop script

- front/src/pages/Profile/index.tsx
#29 
테이블 헤더 설정하고
데이터(row)를 한 줄 씩 삽입하도록 만들었어요
현재 데이터는 하드코딩 상태입니다
테이블 관련 부분을 다른 곳에서 사용할지 여부 확인 후 함수들 적절한 폴더(UI 하위 폴더)로 이동해야하고,
graphql로 데이터 요청해서 가지고 오는 작업 후에 하드코딩 삭제 리팩토링 예정입니다
> feat: add profile pages

- start-server.sh
docker-compose up 이전에 docker image file build를 먼저 해주어야한다.
> feat: start-server build option 추가

- front/src/UI/organisms/CrazyPong/ballMovement.ts
- front/src/UI/organisms/CrazyPong/collision.ts
- front/src/UI/organisms/CrazyPong/data.ts
- front/src/UI/organisms/CrazyPong/index.scss
- front/src/UI/organisms/CrazyPong/index.tsx
- front/src/UI/organisms/CrazyPong/paddleMovement.ts
- front/src/UI/organisms/CrazyPong/utils.tsx
- front/src/pages/Game/index.tsx
figma로 프로토타입을 만든 탁구게임을 만들어보자.
```js
ctx.beginPath();
ctx.arc(x, 75, 50, 0, 2 * Math.PI);
ctx.stroke();
```
위와 같이 패스를 시작해서 arc로 원을 그려주면 stroke로 선을 그어줍니다.
```js
import React, { useRef, useEffect } from 'react';
import './index.scss';
let x = 0;
const CrazyPong = () => {
const canvasRef = useRef<HTMLCanvasElement>(null);
useEffect(() => {
const render = () => {
const canvas = canvasRef.current;
if (canvas) {
const ctx = canvas.getContext('2d');
if (ctx) {
ctx.beginPath();
ctx.arc(x, 75, 50, 0, 2 * Math.PI);
ctx.stroke();
console.log('creating circle');
x++;
requestAnimationFrame(render);
}
}
};
render();
}, []);
return <canvas ref={canvasRef} className="canvas"></canvas>;
};
export default CrazyPong;
```
https://user-images.githubusercontent.com/22424891/124408941-4f3fcb80-dd82-11eb-81c8-b4f2 …
> Crazy pong

- back/src/users/users.resolver.ts
- front/package.json
- front/src/UI/molecules/Alarm/AlarmUser/index.tsx
- front/src/UI/molecules/ProfileSmall/index.tsx
- front/src/UI/organisms/Alarm/index.tsx
- front/src/UI/organisms/AlarmNotifier/AlarmNotifierContainer.tsx
- front/src/UI/organisms/AlarmNotifier/AlarmNotifierPresenter.tsx
- front/src/UI/organisms/AlarmProfile/AlarmProfileContainer.tsx
- front/src/UI/organisms/AlarmProfile/AlarmProfilePresenter.tsx
- front/src/UI/organisms/AlarmProfile/AlarmProfileQueries.ts
- front/src/UI/organisms/AlarmProfile/index.tsx
- front/src/utils/constants.ts
- front/src/utils/dummy.ts
- front/src/utils/interface.ts
- front/yarn.lock
- spinner 추가 
- error 발생시 빨간색 spinner
- loading 시 회색 spinner
https://user-images.githubusercontent.com/22424891/124539047-b0859e80-de57-11eb-8b94-d3a673753281.mov
- profile query 받아오게 로직 추가
> feat: add spinner

- back/schema.gql
- back/src/alarms/alarms.module.ts
- back/src/alarms/alarms.resolver.ts
- back/src/users/users.module.ts
- alarm computed field 구현
- @ResolveField로 선언한 함수는 entities에 선언하지 않아도 자동으로 스키마에 추가된다. (entities에 선언하면안됨)
- @Parent() 는 해당 쿼리값을 매개변수로 받아온다.
```js
@ResolveField(() => User)
user(@Parent() alarm: Alarm) {
return this.usersService.findOne(alarm.userID);
}
```
```graphql
type Alarm {
index: Int!
userID: String!
title: String!
content: String!
checked: String!
type: String!
link: String!
createdAt: DateTime!
user: User!
}
```
- UsersService 를 가져와야한다. 이상하게 가져오면 엄청난 오류의 늪에 빠지게 된다.
```js
// users.module.ts
import { Module } from '@nestjs/common';
import { UsersService } from './users.service';
import { UsersResolver } from './users.resolver';
@Module({
providers: [UsersResolver, UsersService],
exports: [UsersService],
})
export class UsersModule {}
```
```js
// alarms.module.ts
import { Module } …
```
> feat: alarm computed field 기능 구현

- back/schema.gql
- back/src/alarms/alarms.module.ts
- back/src/alarms/alarms.service.ts
- back/src/auth/auth.module.ts
- back/src/auth/guards/gql.guard.ts
- back/src/auth/strategies/jwt.strategy.ts
- back/src/users/users.module.ts
- back/src/users/users.resolver.ts
- back/src/users/users.service.ts
- front/src/UI/organisms/AlarmNotifier/AlarmNotifierContainer.tsx
- front/src/UI/organisms/AlarmNotifier/AlarmNotifierPresenter.tsx
- front/src/UI/organisms/AlarmNotifier/AlarmNotifierQueries.ts
- front/src/UI/organisms/AlarmProfile/AlarmProfileContainer.tsx
- front/src/UI/organisms/AlarmProfile/AlarmProfileQueries.ts
oauth에서 인증된 user로 profile을 query받아오는 코드입니다.
https://github.com/transcendence42/ft_transcendence/issues/54#issuecomment-879840175
위 링크 내용이고 어제 PR로 올라간줄알았는데 사라져서 다시 추가해서 올립니다.
> feat: alarm profile

- back/schema.gql
- back/src/games/dto/update-game.input.ts
- back/src/games/entities/game.entity.ts
- back/src/games/games.resolver.ts
- back/src/games/games.service.ts
> refactor: game -  id to index

- back/schema.gql
- back/src/auth/auth.controller.ts
- front/src/UI/organisms/AlarmProfile/AlarmProfilePresenter.tsx
> feat: logout

- back/schema.gql
- front/src/UI/organisms/GameCardList/GameCardListQuery.ts
세부 사항과 원인은 다음 이슈 참고 
[POST http://127.0.0.1:3000/graphql 400 (Bad Request) 에러 발견](https://github.com/transcendence42/ft_transcendence/issues/118)
POST http://127.0.0.1:3000/graphql 400 (Bad Request) 에러 발견](POST http://127.0.0.1:3000/graphql 400 (Bad Request) 에러 발견
#118 
> fix: 400 bad request (#118)

- front/package.json
- front/src/UI/molecules/Alarm/AlarmUser/index.tsx
- front/yarn.lock
https://user-images.githubusercontent.com/22424891/126741954-42300514-122d-437e-9aff-caa00491930b.mov
contextmenu를 완성했습니다. 제대로된 typescript 버전이 없어서 하나 만들었습니다. ([contextmenu 라이브러리](https://github.com/hochan222/holee-contextmenu))
다음 [링크](https://github.com/hochan222/holee-contextmenu/issues?q=is%3Aissue+is%3Aclosed)의 이슈 사항들이 있습니다. 
크게 주요 사항은 세 가지가 있습니다.
- [rendering이 event 발생 시점에서 한단계씩 늦음](https://github.com/hochan222/holee-contextmenu/issues/11)
- [contextmenu viewport 밖으로 나가면 크기다 달라짐](https://github.com/hochan222/holee-contextmenu/issues/14)
- [contextmenu xposition bug](https://github.com/transcendence42/ft_transcendence/issues/127)
contextmenu 적용
> feat: add contextmenu

- back/schema.gql
- front/src/UI/organisms/Navigation/index.scss
> fix: navigation z-index

- back/schema.gql
- front/src/UI/molecules/ProfileLarge/index.tsx
- front/src/UI/organisms/MainPageHeader/MainPageHeaderQuery.ts
- front/src/UI/organisms/MainPageHeader/index.tsx
- front/src/utils/interface.ts
MainPageHeader LargeProfile 정보 받아와서 반영
> feat: add query on mainPageHeader

- back/schema.gql
- front/src/UI/molecules/Alarm/AlarmChatPeople/index.tsx
- front/src/UI/molecules/Alarm/index.tsx
- front/src/UI/molecules/index.tsx
- front/src/UI/organisms/AlarmChat/index.tsx
- 채팅방 contextmenu
- `채팅방 contextmenu`에서 채팅창을 눌렀을 때
- `채팅방 contextmenu`에서 채팅 인원창을 눌렀을 때
- `owner` 권한 일때
- `admin` 권한 일때
- `user` 권한 일때
- 모든 경우 자기 자신에 대해서는 contextmenu가 나타나지 않습니다.
---
API 로직은 나중에 다른 부분 다 완성되면 짜겠습니다.
```js
const menuOnClickHandler = (
e: React.MouseEvent<HTMLUListElement, MouseEvent> | React.KeyboardEvent<HTMLUListElement>,
) => {
const eventTarget = e.target as HTMLUListElement;
if (eventTarget) {
switch (eventTarget.dataset.option) {
case 'profile':
console.log(eventTarget.dataset.option);
break;
case 'send-message':
console.log(eventTarget.dataset.option);
break;
case 'add-friend':
console.log(eventTarget.dataset.option);
break;
case 'play-game':
console.log(eventTarget.dataset.option);
break;
case 'register-admin':
console.log(eventTarget.dataset.option);
break;
case …
```
> feat: alarm chat people

- front/src/UI/molecules/ProfileLarge/index.tsx
- front/src/UI/organisms/MainPageHeader/index.tsx
- front/src/utils/interface.ts
profile large 수정
- 표기 방식 변경
- userID -> nickname(userID)
- interface 이름 변경
- ProfileLargeProps -> IProfileLarge
> refactor: profile large

- back/src/users/users.resolver.ts
- back/src/users/users.service.ts
getMyLadderRanking 내 랭킹
getLadderRanking(userID) 특정 유저의 랭킹
이후에 각 사이즈별 프로필에 랭킹 필요하니 그에 맞춰 업데이트 하겠습니다.
----
기본 테스트 (yshin 1300, yechoi 1200, holee 1100, jwon 1000)
중복 스코어 테스트 (yshin 1300, yechoi 1200, holee 1300, jwon 1000)
-> 동일 순위자가 존재할 경우 그 다음 순위를 건너뜀 (1위가 2명일 경우 2위는 없음)
참고링크
RANK, DENSE RANK
https://www.postgresqltutorial.com/postgresql-rank-function/
https://www.postgresqltutorial.com/postgresql-dense_rank-function/
> feat: add getLadderRanking query

- back/.eslintrc.js
- back/src/follows/follows.service.ts
- front/src/UI/molecules/Alarm/AlarmChatPeople/AlarmChatPeopleQueries.ts
- front/src/UI/molecules/Alarm/AlarmChatPeople/index.tsx
채팅인원창에서 특정 유저에 대해 '친구 추가 요청' 버튼을 클릭하면 해당 유저에게 친구 추가 요청 알람이 보내집니다.
채팅인원창에서 특정 유저에 대해 '메시지 보내기' 버튼을 클릭하면 해당 유저에게 알람이 보내집니다.
채팅인원창에서 특정 유저에 대해 '프로필 보기' 버튼을 클릭하면 해당 유저의 프로필 페이지로 이동합니다.
> feat: 채팅인원창 '메시지 보내기, 프로필 보기, 친구 추가 요청'

- back/src/chats/chats.service.ts
- front/src/UI/organisms/AlarmChat/index.tsx
- front/src/UI/organisms/AlarmChatPasswordManage/AlarmChatPasswordManageQueries.ts
- front/src/UI/organisms/AlarmChatPasswordManage/index.tsx
- front/src/UI/organisms/ChatTableRow/ChatTableRowQueries.ts
- front/src/UI/organisms/ChatTableRow/index.tsx
사용자가 채팅방의 방장(owner)인 경우, 해당 채팅방의 비밀번호를 추가/삭제/변경 할 수 있습니다.
사용자가 채팅방의 방장인 경우 다음과 같이 '채팅 패스워드 관리' 라는 컨텍스트 메뉴를 클릭할 수 있습니다.
'채팅 패스워드 관리' 메뉴를 클릭하면 다음과 같은 modal이 출력됩니다.
cf) 채팅방의 방장이 아니라면 기존과 동일한 컨텍스트 메뉴가 노출됩니다.
비밀번호를 추가하려면 비공개 버튼을 누르고 아래 입력칸에 비밀번호를 입력하여 적용 버튼을 누르면 비밀번호가 설정됩니다.
비밀번호를 변경하려면 비공개 버튼을 누르고 아래 입력칸에 비밀번호를 입력하여 적용 버튼을 클릭합니다.
비밀번호 적용을 해제하려면 공개 버튼을 누르고 적용 버튼을 클릭합니다.
> feat: 채팅방 비밀번호 관리

- back/schema.gql
- back/src/alarms/alarms.resolver.ts
- back/src/auth/auth.controller.ts
- back/src/chat-logs/chat-logs.resolver.ts
- back/src/chat-logs/chat-logs.service.ts
- back/src/chats/dto/create-chat.input.ts
- back/src/chats/dto/update-chat.input.ts
- back/src/chats/entities/chat.entity.ts
- back/src/follows/dto/create-follow.input.ts
- back/src/follows/dto/update-follow.input.ts
- back/src/follows/entities/follow.entity.ts
- back/src/games/dto/create-game.input.ts
- back/src/games/entities/game.entity.ts
- back/src/games/games.module.ts
- back/src/games/games.resolver.ts
- back/src/games/games.service.ts
- back/src/main.ts
- back/src/playing-info/dto/create-playing-info.input.ts
- back/src/playing-info/entities/playing-info.entity.ts
- back/src/playing-info/playing-info.module.ts
- back/src/playing-info/playing-info.resolver.ts
- back/src/playing-info/playing-info.service.ts
- back/src/users/entities/user.entity.ts
- back/src/users/users.resolver.ts
- back/test/app.e2e-spec.ts
- front/src/UI/molecules/MainButtons/index.tsx
- front/src/UI/organisms/CrazyPong/CrazyPongContainer.tsx
- front/src/UI/organisms/CrazyPong/CrazyPongQuery.tsx
- front/src/pages/Game/GameQuery.tsx
- front/src/pages/Game/index.tsx
Co-authored-by: hochan222 <hochan049@gmail.com>
- 게임 시작 버튼을 누른다
- 매칭된 플레이어의 화면에 게임이 뜬다
- game와 playingInfo 의 uuid는 동기화돼있다
> feat: game - playingInfo sync
